In [5]:
import pandas as pd 
df = pd.read_csv("Time Americans Spend Sleeping.csv")
df

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both
...,...,...,...,...,...,...,...,...,...
940,940,2013,Annual,8.83,0.085,Nonholiday weekdays,65 years and over,Sleeping,Women
941,941,2014,Annual,8.98,0.086,Nonholiday weekdays,65 years and over,Sleeping,Women
942,942,2015,Annual,8.83,0.074,Nonholiday weekdays,65 years and over,Sleeping,Women
943,943,2016,Annual,8.92,0.071,Nonholiday weekdays,65 years and over,Sleeping,Women
944,944,2017,Annual,8.81,0.091,Nonholiday weekdays,65 years and over,Sleeping,Women

In [6]:
df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [7]:
df.describe()

            index         Year  Avg hrs per day sleeping  Standard Error
count  945.000000   945.000000                945.000000      945.000000
mean   472.000000  2010.000000                  8.806868        0.086958
std    272.942302     4.322782                  0.545001        0.034631
min      0.000000  2003.000000                  7.720000        0.018000
25%    236.000000  2006.000000                  8.360000        0.063000
50%    472.000000  2010.000000                  8.810000        0.084000
75%    708.000000  2014.000000                  9.190000        0.106000
max    944.000000  2017.000000                 10.650000        0.228000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    object
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    object
 6   Age Group                 945 non-null    object
 7   Activity                  945 non-null    object
 8   Sex                       945 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 66.6+ KB

The column ‘Avg hrs per day sleeping’ is a good choice for prediction because it is the main quantitative outcome variable in the dataset. It represents how much people sleep on average and varies across years, age groups, and sexes, making it suitable for trend forecasting or regression modeling. Other relevant columns that support this analysis include ‘Year’ (for trend analysis), ‘Age Group’ and ‘Sex’ (for group comparison), and ‘Type of Days’ (to analyze differences between weekdays and weekends).